---
title: "processing"
author: "Charles Hendrickson"
date: '2022-06-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load libraries 
#install and load librarian package if needed 
if (!require(librarian)) {
  install.packages("librarian")
  library(librarian)
}

# load packages
librarian::shelf(tidyverse,
                 janitor,
                 dplyr, 
                 naniar,
                 here)
```


```{r}
#process 2020 complete data 
acm_2020_complete <- read.delim2(here("raw_data/Mortality_Statistics_2020_Complete.txt")) %>% 
  clean_names() %>% 
  select(-c(notes)) %>% 
  rename(county =  "residence_county") %>% 
  separate(county, into = c("county", "state"), sep = ", ") %>%
  mutate(county = str_remove_all(string = county, pattern = " County")) %>% 
  rename(county_code = "residence_county_code")

#add year column 
acm_2020_complete$year <- 2020

```

```{r}
#Next, lets check out the missing data values in the data using the `naniar` package, which provides useful functions for examining initial missing value counts and proportions. 

# Returns NA count in your data frame or column
n_miss(acm_2020_complete)

# Returns number of complete values
n_complete(acm_2020_complete)

# Proportion or percentage of values that are NA
prop_miss(acm_2020_complete) 

pct_miss(acm_2020_complete)

# A summary table of NA counts in your table
miss_var_summary(acm_2020_complete)

# A summary table of NAs by case (observation)
miss_case_table(acm_2020_complete)

# Remove all rows with missing values
acm_2020_complete <- na.omit(acm_2020_complete)

# check to see if missing values have been dropped
pct_miss(acm_2020_complete)

# Alternatively could remove specific obseravtions with missing values  
#acm_2020_complete <- acm_2020_complete[!is.na(acm_2020_complete$state), ]

# Confirm that NA's were removed from state column
#pct_miss(MCR_LTER_bleaching_data_clean$Percent_bleached)
```
```{r}
#create lag time
acm_2020_complete <- acm_2020_complete %>% 
group_by(county_code) %>% 
  mutate(death_rate_lag1 = c(crude_rate[-1], NA)) %>% 
  ungroup() %>% 
  filter(year == 2020)
```

```{r}
#make csv file 
  acm_2020_complete %>% write_csv(file.path(here("final_data/2020_ACM_complete.csv")))

```



